# Generated by Django 3.1.5 on 2021-01-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EventGeneration.user')),
                ('roll_no', models.IntegerField()),
                ('college_id', models.CharField(max_length=10)),
                ('cpi', models.CharField(max_length=4)),
            ],
        ),
    ]
