# Generated by Django 3.1.5 on 2021-01-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0003_auto_20210112_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
