# Generated by Django 3.1.5 on 2021-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college_id',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
