# Generated by Django 3.1.5 on 2021-01-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0006_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='event_id',
        ),
        migrations.AddField(
            model_name='mapping',
            name='event_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='EventGeneration.event'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mapping',
            name='user_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='EventGeneration.user'),
            preserve_default=False,
        ),
    ]
