# Generated by Django 3.1.5 on 2021-02-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0008_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventGeneration.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='in_team',
            field=models.BooleanField(default=False),
        ),
    ]
