# Generated by Django 3.1.5 on 2021-01-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventGeneration', '0008_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('own_def', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventGeneration.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_members', models.TextField(max_length=50)),
                ('preference1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_1', to='ProjectAllocation.project')),
                ('preference2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_2', to='ProjectAllocation.project')),
                ('preference3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_3', to='ProjectAllocation.project')),
                ('preference4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_4', to='ProjectAllocation.project')),
                ('preference5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_5', to='ProjectAllocation.project')),
            ],
        ),
    ]
