# Generated by Django 3.1.5 on 2021-02-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0008_faculty'),
        ('ProjectAllocation', '0002_team_highest_cpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='highest_cpi',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='member1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_1', to='EventGeneration.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='member_2', to='EventGeneration.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='member3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_3', to='EventGeneration.student'),
        ),
    ]
