# Generated by Django 3.1.5 on 2021-02-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0008_faculty'),
        ('ProjectAllocation', '0003_auto_20210201_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventGeneration.faculty'),
        ),
    ]
