# Generated by Django 3.1.5 on 2021-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAllocation', '0004_auto_20210212_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='highest_cpi',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
