# Generated by Django 3.1.5 on 2021-02-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAllocation', '0005_team_highest_cpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocated_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAllocation.project')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectAllocation.team')),
            ],
        ),
    ]
