# Generated by Django 3.1.5 on 2021-02-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventGeneration', '0009_auto_20210226_1333'),
        ('ProjectAllocation', '0007_auto_20210226_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventGeneration.student'),
        ),
    ]
